name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build Release
      run: dotnet build --configuration Release --no-restore
      
    - name: Publish Self-Contained
      run: dotnet publish --configuration Release --runtime win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
      
    - name: Create Release Archive
      run: |
        cd bin/Release/net6.0-windows/win-x64/publish
        7z a ../../../../../MTGAFullscreenHelper-win-x64.zip *
        
    - name: Upload Release Assets
      uses: actions/upload-artifact@v4
      with:
        name: MTGAFullscreenHelper-win-x64
        path: MTGAFullscreenHelper-win-x64.zip
        
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: MTGAFullscreenHelper-win-x64.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}